name: Cypress Tests with Code Coverage

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev:coverage
          wait-on: "http://localhost:3000"
          wait-on-timeout: 180
          command: yarn cypress:run