name: Portfolio QA Tests

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  portfolio-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Start application
        run: |
          yarn dev:coverage &

      - name: Wait for frontend
        run: npx wait-on http://localhost:3000 --timeout 180000

      - name: Wait for backend
        run: npx wait-on http://localhost:3001 --timeout 180000

      - name: Test seed endpoint
        run: |
          curl -X POST http://localhost:3001/testData/seed

      - name: Run Cypress tests
        run: yarn cypress:run

